paths:
  clone_dir: "/home/ioi/cms-data"
  requests_dir: "/var/lib/gitolite3/requests"
  lock_file: "/home/ioi/cms-data/.lock"

locks:
  lifetime: 3600
  timeout: 150

requests:
  cooling_period: 15
  active_contests: ["contests/testing"]
