paths:
  clone_dir: "/home/ioi/cms-data"
  tasks_dir: "/home/ioi/cms-data/tasks"
  contests_dir: "/home/ioi/cms-data/contests"
  users_file: "/home/ioi/cms-data/users/users-2018.yaml"
  requests_dir: "/var/lib/gitolite3/requests"
  lock_file: "/home/ioi/cms-data/.lock"

locks:
  lifetime: 3600
  timeout: 150
